name: Test Pages Function

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Avenlo Pages Function
        run: |
          echo "========== AVENLO PAGES TEST =========="

          URL="https://c60af14d.avenlo.pages.dev/check?sstp=vpn:vpn@127.0.0.1%3A443"

          echo "请求 URL:"
          echo "$URL"

          echo
          echo "========== RESPONSE =========="

          curl -i --max-time 30 "$URL"

          echo
          echo "================================"
